image: node:latest

stages:
  - deploy
  
  
deploy:
  type: deploy
  stage: deploy
  script:
    - cd 'no-waste-app'
    - npm install
    - npm install -g @angular/cli
    - ng build --aot --prod
    - cp server.js dist
    - cd dist
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-app --api-key=$HEROKU_API_KEY
  only:
    - master
        