image: node:latest

stages:
  - build
  - deploy
  
build:
  type: deploy
  stage: build
  image: node:latest
  script:
    - cd no-waste-app
    - npm install
    - npm install -g @angular/cli
    - ng build
  only:
    - master
        

deploy:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - cd 'no-waste-app/dist/no-waste-app'
    - ls
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-app --api-key=$HEROKU_API_KEY
  only:
    - master
        