image: node:latest

cache:
    paths:
      - 'no-waste-app/deploy-folder'

stages:
  - build
  - test
  - deploy
  
build:
  type: build
  stage: build
  script:
    - cd 'no-waste-app'
    - npm install
    - npm install -g @angular/cli
    - ng build --aot --prod
    - rm -rf deploy-folder
    - mkdir deploy-folder
    - cp -R dist deploy-folder
    - cp server.js deploy-folder
    - cd deploy-folder
    - npm init -f
    - npm install
    - npm install --save express
  only:
    - master
    
test:
  type: test
  stage: test
  script:
    - cd 'no-waste-app/deploy-folder'
    - ls
  only:
    - master
          
deploy:
  type: deploy
  stage: deploy
  script:
    - cd 'no-waste-app/deploy-folder'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-app --api-key=$HEROKU_API_KEY
  only:
    - master
        