image: ruby:latest

stages:
  - deploy
  
deploy:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - cd 'no-waste-app'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-app --api-key=$HEROKU_API_KEY
  only:
    - master
        