image: node:latest

stages:
  - production
  
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - cd no-waste-app
    - npm install
    - ng build
    - cd dist/no-waste-app
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-app --api-key=$HEROKU_API_KEY
  only:
    - master
        
