image: node:latest

stages:
  - build-api
  - test-api
  - deploy-api

build-api:
  type: build
  stage: build
  script:
    - cd 'no-waste-api'
  only:
    - master

test-api:
  type: test
  stage: test
  script:
    - cd 'no-waste-api'
  only:
    - master

deploy-api:
  type: deploy
  stage: deploy
  script:
    - cd 'no-waste-api'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-api --api-key=$HEROKU_API_KEY
  only:
    - master
