image: node:latest

stages:
  - build
  - test
  - deploy

build-api:
  type: build
  stage: build-api
  script:
    - cd 'no-waste-api'
  only:
    - master

test-api:
  type: test
  stage: test-api
  script:
    - cd 'no-waste-api'
  only:
    - master

deploy-api:
  type: deploy
  stage: deploy-api
  script:
    - cd 'no-waste-api'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-api --api-key=$HEROKU_API_KEY
  only:
    - master
