image: node:latest

cache:
    paths:
      - 'no-waste-app/deploy-folder'

stages:
  - build-app
  - test-app
  - deploy-app
  
build-app:
  type: build
  stage: build-app
  script:
    - cd 'no-waste-app'
    - npm install
    - npm install -g @angular/cli
    - ng build --aot --prod
    - rm -rf deploy-folder
    - mkdir deploy-folder
    - cp -R dist deploy-folder
    - cp server.js deploy-folder
    - cp package.json deploy-folder
    - cd deploy-folder
    - npm install
  only:
    - master
    
test-app:
  type: test
  stage: test-app
  script:
    - cd 'no-waste-app/deploy-folder'
    - ls
  only:
    - master
          
deploy-app:
  type: deploy
  stage: deploy-app
  script:
    - cd 'no-waste-app'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=no-waste-app --api-key=$HEROKU_API_KEY
  only:
    - master
